/*
Copyright (c) 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apisv1alpha1 "github.com/kubernetes-sigs/multi-network-api/apis/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NetworkKindLister helps list NetworkKinds.
// All objects returned here must be treated as read-only.
type NetworkKindLister interface {
	// List lists all NetworkKinds in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisv1alpha1.NetworkKind, err error)
	// Get retrieves the NetworkKind from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apisv1alpha1.NetworkKind, error)
	NetworkKindListerExpansion
}

// networkKindLister implements the NetworkKindLister interface.
type networkKindLister struct {
	listers.ResourceIndexer[*apisv1alpha1.NetworkKind]
}

// NewNetworkKindLister returns a new NetworkKindLister.
func NewNetworkKindLister(indexer cache.Indexer) NetworkKindLister {
	return &networkKindLister{listers.New[*apisv1alpha1.NetworkKind](indexer, apisv1alpha1.Resource("networkkind"))}
}
