/*
Copyright (c) 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apisv1alpha1 "github.com/kubernetes-sigs/multi-network-api/apis/v1alpha1"
	scheme "github.com/kubernetes-sigs/multi-network-api/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NetworkKindsGetter has a method to return a NetworkKindInterface.
// A group's client should implement this interface.
type NetworkKindsGetter interface {
	NetworkKinds() NetworkKindInterface
}

// NetworkKindInterface has methods to work with NetworkKind resources.
type NetworkKindInterface interface {
	Create(ctx context.Context, networkKind *apisv1alpha1.NetworkKind, opts v1.CreateOptions) (*apisv1alpha1.NetworkKind, error)
	Update(ctx context.Context, networkKind *apisv1alpha1.NetworkKind, opts v1.UpdateOptions) (*apisv1alpha1.NetworkKind, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, networkKind *apisv1alpha1.NetworkKind, opts v1.UpdateOptions) (*apisv1alpha1.NetworkKind, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apisv1alpha1.NetworkKind, error)
	List(ctx context.Context, opts v1.ListOptions) (*apisv1alpha1.NetworkKindList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apisv1alpha1.NetworkKind, err error)
	NetworkKindExpansion
}

// networkKinds implements NetworkKindInterface
type networkKinds struct {
	*gentype.ClientWithList[*apisv1alpha1.NetworkKind, *apisv1alpha1.NetworkKindList]
}

// newNetworkKinds returns a NetworkKinds
func newNetworkKinds(c *MultinetworkV1alpha1Client) *networkKinds {
	return &networkKinds{
		gentype.NewClientWithList[*apisv1alpha1.NetworkKind, *apisv1alpha1.NetworkKindList](
			"networkkinds",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *apisv1alpha1.NetworkKind { return &apisv1alpha1.NetworkKind{} },
			func() *apisv1alpha1.NetworkKindList { return &apisv1alpha1.NetworkKindList{} },
		),
	}
}
