/*
Copyright (c) 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apisv1alpha1 "github.com/kubernetes-sigs/multi-network-api/apis/v1alpha1"
	scheme "github.com/kubernetes-sigs/multi-network-api/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PodNetworkKindsGetter has a method to return a PodNetworkKindInterface.
// A group's client should implement this interface.
type PodNetworkKindsGetter interface {
	PodNetworkKinds() PodNetworkKindInterface
}

// PodNetworkKindInterface has methods to work with PodNetworkKind resources.
type PodNetworkKindInterface interface {
	Create(ctx context.Context, podNetworkKind *apisv1alpha1.PodNetworkKind, opts v1.CreateOptions) (*apisv1alpha1.PodNetworkKind, error)
	Update(ctx context.Context, podNetworkKind *apisv1alpha1.PodNetworkKind, opts v1.UpdateOptions) (*apisv1alpha1.PodNetworkKind, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, podNetworkKind *apisv1alpha1.PodNetworkKind, opts v1.UpdateOptions) (*apisv1alpha1.PodNetworkKind, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apisv1alpha1.PodNetworkKind, error)
	List(ctx context.Context, opts v1.ListOptions) (*apisv1alpha1.PodNetworkKindList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apisv1alpha1.PodNetworkKind, err error)
	PodNetworkKindExpansion
}

// podNetworkKinds implements PodNetworkKindInterface
type podNetworkKinds struct {
	*gentype.ClientWithList[*apisv1alpha1.PodNetworkKind, *apisv1alpha1.PodNetworkKindList]
}

// newPodNetworkKinds returns a PodNetworkKinds
func newPodNetworkKinds(c *MultinetworkV1alpha1Client) *podNetworkKinds {
	return &podNetworkKinds{
		gentype.NewClientWithList[*apisv1alpha1.PodNetworkKind, *apisv1alpha1.PodNetworkKindList](
			"podnetworkkinds",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *apisv1alpha1.PodNetworkKind { return &apisv1alpha1.PodNetworkKind{} },
			func() *apisv1alpha1.PodNetworkKindList { return &apisv1alpha1.PodNetworkKindList{} },
		),
	}
}
