/*
Copyright (c) 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubernetes-sigs/multi-network-api/apis/v1alpha1"
	apisv1alpha1 "github.com/kubernetes-sigs/multi-network-api/pkg/client/clientset/versioned/typed/apis/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakePodNetworkKinds implements PodNetworkKindInterface
type fakePodNetworkKinds struct {
	*gentype.FakeClientWithList[*v1alpha1.PodNetworkKind, *v1alpha1.PodNetworkKindList]
	Fake *FakeMultinetworkV1alpha1
}

func newFakePodNetworkKinds(fake *FakeMultinetworkV1alpha1) apisv1alpha1.PodNetworkKindInterface {
	return &fakePodNetworkKinds{
		gentype.NewFakeClientWithList[*v1alpha1.PodNetworkKind, *v1alpha1.PodNetworkKindList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("podnetworkkinds"),
			v1alpha1.SchemeGroupVersion.WithKind("PodNetworkKind"),
			func() *v1alpha1.PodNetworkKind { return &v1alpha1.PodNetworkKind{} },
			func() *v1alpha1.PodNetworkKindList { return &v1alpha1.PodNetworkKindList{} },
			func(dst, src *v1alpha1.PodNetworkKindList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.PodNetworkKindList) []*v1alpha1.PodNetworkKind {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.PodNetworkKindList, items []*v1alpha1.PodNetworkKind) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
