/*
Copyright (c) 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	multinetworkapiapisv1alpha1 "github.com/kubernetes-sigs/multi-network-api/apis/v1alpha1"
	versioned "github.com/kubernetes-sigs/multi-network-api/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubernetes-sigs/multi-network-api/pkg/client/informers/externalversions/internalinterfaces"
	apisv1alpha1 "github.com/kubernetes-sigs/multi-network-api/pkg/client/listers/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodNetworkKindInformer provides access to a shared informer and lister for
// PodNetworkKinds. Prefer using the type-safe variant (see [TypedPodNetworkKindInformer]).
type PodNetworkKindInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apisv1alpha1.PodNetworkKindLister
}

// TypedPodNetworkKindInformer provides access to a shared informer and lister for
// PodNetworkKinds, including the type-safe TypedInformer variant.
// It is a superset of PodNetworkKindInformer.
type TypedPodNetworkKindInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() PodNetworkKindIndexInformer
	Lister() apisv1alpha1.PodNetworkKindLister
}

// PodNetworkKindIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type PodNetworkKindIndexInformer cache.TypedSharedIndexInformer[*multinetworkapiapisv1alpha1.PodNetworkKind]

// PodNetworkKindHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for PodNetworkKind.
type PodNetworkKindHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*multinetworkapiapisv1alpha1.PodNetworkKind]

// PodNetworkKindDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for PodNetworkKind.
type PodNetworkKindDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*multinetworkapiapisv1alpha1.PodNetworkKind]

// PodNetworkKindFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for PodNetworkKind.
type PodNetworkKindFilteringHandler = cache.TypedFilteringResourceEventHandler[*multinetworkapiapisv1alpha1.PodNetworkKind]

// PodNetworkKindIndexers is a specialization of [cache.TypedIndexers] for PodNetworkKind.
type PodNetworkKindIndexers = cache.TypedIndexers[*multinetworkapiapisv1alpha1.PodNetworkKind]

// DeletedPodNetworkKind is a specialization of [cache.DeletedObject] for PodNetworkKind.
type DeletedPodNetworkKind = cache.DeletedObject[*multinetworkapiapisv1alpha1.PodNetworkKind]

type podNetworkKindInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewPodNetworkKindInformer constructs a new informer for PodNetworkKind type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedPodNetworkKindInformer]).
func NewPodNetworkKindInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewPodNetworkKindInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedPodNetworkKindInformer constructs a new informer for PodNetworkKind type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedPodNetworkKindInformer(client versioned.Interface, resyncPeriod time.Duration, indexers PodNetworkKindIndexers) PodNetworkKindIndexInformer {
	return NewTypedPodNetworkKindInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredPodNetworkKindInformer constructs a new informer for PodNetworkKind type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredPodNetworkKindInformer]).
func NewFilteredPodNetworkKindInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedPodNetworkKindInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredPodNetworkKindInformer constructs a new informer for PodNetworkKind type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredPodNetworkKindInformer(client versioned.Interface, resyncPeriod time.Duration, indexers PodNetworkKindIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) PodNetworkKindIndexInformer {
	return NewTypedPodNetworkKindInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewPodNetworkKindInformerWithOptions constructs a new informer for PodNetworkKind type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedPodNetworkKindInformerWithOptions]).
func NewPodNetworkKindInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedPodNetworkKindInformerWithOptions(client, options)
}

// NewTypedPodNetworkKindInformerWithOptions constructs a new informer for PodNetworkKind type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedPodNetworkKindInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) PodNetworkKindIndexInformer {
	gvr := schema.GroupVersionResource{Group: "multinetwork.networking.x-k8s.io", Version: "v1alpha1", Resource: "podnetworkkinds"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*multinetworkapiapisv1alpha1.PodNetworkKind](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.MultinetworkV1alpha1().PodNetworkKinds().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.MultinetworkV1alpha1().PodNetworkKinds().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.MultinetworkV1alpha1().PodNetworkKinds().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.MultinetworkV1alpha1().PodNetworkKinds().Watch(ctx, opts)
			},
		}, client),
		&multinetworkapiapisv1alpha1.PodNetworkKind{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *podNetworkKindInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedPodNetworkKindInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *podNetworkKindInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *podNetworkKindInformer) TypedInformer() PodNetworkKindIndexInformer {
	return cache.NewTypedSharedIndexInformer[*multinetworkapiapisv1alpha1.PodNetworkKind](f.factory.InformerFor(&multinetworkapiapisv1alpha1.PodNetworkKind{}, f.defaultInformer))
}

func (f *podNetworkKindInformer) Lister() apisv1alpha1.PodNetworkKindLister {
	return apisv1alpha1.NewPodNetworkKindLister(f.Informer().GetIndexer())
}

// ToTypedPodNetworkKindInformer converts an untyped informer into a TypedPodNetworkKindInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *PodNetworkKind. If that is not the case, calling type-safe methods of the returned
// TypedPodNetworkKindInformer leads to runtime panics. A safer alternative is to pass
// around a TypedPodNetworkKindInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedPodNetworkKindInformer(informer PodNetworkKindInformer) TypedPodNetworkKindInformer {
	if informer, ok := informer.(TypedPodNetworkKindInformer); ok {
		return informer
	}
	return &podNetworkKindTypedInformerAdapter{informer}
}

type podNetworkKindTypedInformerAdapter struct {
	PodNetworkKindInformer
}

func (a *podNetworkKindTypedInformerAdapter) TypedInformer() PodNetworkKindIndexInformer {
	return cache.NewTypedSharedIndexInformer[*multinetworkapiapisv1alpha1.PodNetworkKind](a.Informer())
}

// ToPodNetworkKindIndexInformer converts an untyped informer into a PodNetworkKindIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *PodNetworkKind. If that is not the case, calling type-safe methods of the returned
// PodNetworkKindIndexInformer leads to runtime panics. A safer alternative is to pass
// around a PodNetworkKindIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToPodNetworkKindIndexInformer(informer cache.SharedIndexInformer) PodNetworkKindIndexInformer {
	if informer, ok := informer.(PodNetworkKindIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*multinetworkapiapisv1alpha1.PodNetworkKind](informer)
}
